// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTSeVOwpDxwYs6a4YErrIeCL0OVwD8no',
    appId: '1:799713381259:web:4c8c123f23324067ef7d8e',
    messagingSenderId: '799713381259',
    projectId: 'flutter-fb-chat-project',
    authDomain: 'flutter-fb-chat-project.firebaseapp.com',
    storageBucket: 'flutter-fb-chat-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYWilXmBTHUCF2I7aOA_CjzvuHM5IbRq0',
    appId: '1:799713381259:android:127c687f1b873911ef7d8e',
    messagingSenderId: '799713381259',
    projectId: 'flutter-fb-chat-project',
    storageBucket: 'flutter-fb-chat-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jpZwK6cTt-8-ujLzrEMxqKkJqD5cI0s',
    appId: '1:799713381259:ios:f05d11fc0720116cef7d8e',
    messagingSenderId: '799713381259',
    projectId: 'flutter-fb-chat-project',
    storageBucket: 'flutter-fb-chat-project.appspot.com',
    iosBundleId: 'com.example.chatSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9jpZwK6cTt-8-ujLzrEMxqKkJqD5cI0s',
    appId: '1:799713381259:ios:87477e09e05e4566ef7d8e',
    messagingSenderId: '799713381259',
    projectId: 'flutter-fb-chat-project',
    storageBucket: 'flutter-fb-chat-project.appspot.com',
    iosBundleId: 'com.example.chatSample.RunnerTests',
  );
}
